### PR TITLE
Detect use of patched library, Mac static linking

### PR DESCRIPTION
**Pull request by StanGirard**
Adding -mt on mac  worked for me.

Just tried with 12 threads and 100k moduli. worked like a charm

### CODE REVIEW

**Comment by StanGirard** [comment]
And I removed -static

**Comment by zugzwang** [comment]
Hello Stan, 

- Apparently, the `-mt` suffix for the `boost_thread` library [has been removed](https://askubuntu.com/questions/486006/cannot-find-boost-thread-mt-library). I cannot compile in Ubuntu with `-lboost_thread-mt`. Are sure that you have the latest `boost_thread`?
- If I remove the `static` linking flag, it compiles and runs, but it does not use the patched library (therefore you have the ~4M limit). 

Could you find a solution that uses the patched library? (i.e., `gmp.h` link inside `gmp/patched/lib`). I acknowledge the `makefile` is not ideal (was using `CMake` but run into problems with multithreading libraries).

**Comment by StanGirard** [comment]
Well, i'm not an expert with Makefiles but an issue i found is that macos doesn't support -static. Is there any other way to link the patch without using static ?

**Comment by StanGirard** [comment]
The basic installation of boost with `brew install boost` should have installed everything. 
But the only way of getting it to work i found for now is with -mt 

Not an expert so I ask, I removed -static but your are linking to the patched gmp libraries with `-I./gmp/patched/include/` and ` -L./gmp/patched/lib`?  Is static really necessary ?

**Comment by zugzwang** [comment]
Hi, maybe I should update the patch in order to create two functions, `mpz_inp_raw_64` and `mpz_out_raw_64` instead of replacing the body of `mpz_inp_raw`, `mpz_out_raw`, and then have `batchgcd.cpp` to detect if those functions are available. This is what `factorable.net` patch does, actually.
With this, you will be able to test whether your makefile is linking against the patched library or not.

**Comment by zugzwang** [comment]
Renamed and broaden the scope of this PR in order to address this.

**Comment by StanGirard** [comment]
> Hi, maybe I should update the patch in order to create two functions, `mpz_inp_raw_64` and `mpz_out_raw_64` instead of replacing the body of `mpz_inp_raw`, `mpz_out_raw`, and then have `batchgcd.cpp` to detect if those functions are available. This is what `factorable.net` patch does, actually.
> With this, you will be able to test whether your makefile is linking against the patched library or not.

That would be a great idea. I think it is a better way of patching.

**Pull request merged**
